/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.NhanVienDao;
import UTILS.Auth;
import UTILS.MsgBox;
import UTILS.XImage;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DoiMatKhauJDialog extends java.awt.Dialog {

    NhanVienDao dao = new NhanVienDao();

    /**
     * Creates new form DoiMatKhauJDialog
     */
    public DoiMatKhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    void init() {
        setTitle("Đỗi Mật Khẩu");
        setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(null);
        txtMaNV.setText(Auth.user.getMaNV());
        this.clear();
    }

    String code() {
        String maCode = "";
        String[] ma = {"a", "b", "c", "d", "e", "f", "g", "h", "i", "k", "m", "n", "w", "x", "y",
            "A", "B", "C", "D", "E", "F", "G", "H", "K", "O", "Q", "W", "P", "L", "M",
            "N", "X", "Y", "1", "2", "3", "4", "5", "6", "7", "8", "9"};
        Random rd = new Random();
        for (int i = 0; i < 6; i++) {
            maCode += ma[rd.nextInt(ma.length)]; //Cộng và gán giá trị
        }
        txtCode.setText(maCode);
        return maCode;
    }

    private void doiMatKhau() {
        String matKhau = new String(txtMatKhauCu.getPassword());
        String matKhauMoi1 = new String(txtMatKhauMoi1.getPassword());
        String matKhauMoi2 = new String(txtMatKhauMoi2.getPassword());
        String nhapcode = txtNhapCode.getText();
        String code = txtCode.getText();
        if (!matKhau.equals(Auth.user.getMatKhau())) {
            MsgBox.alert(this, "Sai mật khẩu!");
        } else if (!matKhauMoi1.equals(matKhauMoi2)) {
            MsgBox.alert(this, "Xác nhận mật khẩu không đúng!");
        }else if (!nhapcode.equals(code)) {
            MsgBox.alert(this, "Nhập sai mã code");
        }  else {
            Auth.user.setMatKhau(matKhauMoi1);
            dao.update(Auth.user);
            MsgBox.alert(this, "Đổi mật khẩu thành công!");
            this.clear();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDMK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMatKhauMoi1 = new javax.swing.JPasswordField();
        txtMatKhauCu = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        ckbHien = new javax.swing.JCheckBox();
        btnCode = new javax.swing.JButton();
        txtMatKhauMoi2 = new javax.swing.JPasswordField();
        txtCode = new javax.swing.JTextField();
        txtNhapCode = new javax.swing.JTextField();

        setBackground(new java.awt.Color(240, 240, 240));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        btnDMK.setBackground(new java.awt.Color(255, 204, 204));
        btnDMK.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh.png"))); // NOI18N
        btnDMK.setText("Đổi Mật Khẩu");
        btnDMK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDMK.setDoubleBuffered(true);
        btnDMK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDMK.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnDMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMKActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Mã Nhân Viên:");

        txtMaNV.setEditable(false);
        txtMaNV.setBackground(new java.awt.Color(250, 250, 250));
        txtMaNV.setEnabled(false);

        btnHuy.setBackground(new java.awt.Color(255, 204, 204));
        btnHuy.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHuy.setDoubleBuffered(true);
        btnHuy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuy.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Mật Khẩu Cũ:");
        jLabel3.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Mật Khẩu Mới:");

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Nhập lại mật khẩu mới:");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Đổi Mật Khẩu");

        ckbHien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckbHien.setText("Hiện Mật Khẩu");
        ckbHien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbHienActionPerformed(evt);
            }
        });

        btnCode.setBackground(new java.awt.Color(255, 204, 204));
        btnCode.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh.png"))); // NOI18N
        btnCode.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCode.setDoubleBuffered(true);
        btnCode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCode.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeActionPerformed(evt);
            }
        });

        txtCode.setEditable(false);
        txtCode.setBackground(new java.awt.Color(250, 250, 250));
        txtCode.setEnabled(false);

        txtNhapCode.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ckbHien)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap(283, Short.MAX_VALUE)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap(138, Short.MAX_VALUE)
                                    .addComponent(btnDMK)
                                    .addGap(75, 75, 75)
                                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(txtMatKhauCu)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(txtMatKhauMoi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txtMatKhauMoi2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNhapCode))))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatKhauMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatKhauMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCode, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtNhapCode))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDMK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHuy, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckbHien)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnDMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMKActionPerformed
//         TODO add your handling code here:
        if (validated()) {
            doiMatKhau();
        }


    }//GEN-LAST:event_btnDMKActionPerformed
    boolean validated() {
        if (txtMaNV.getText().isEmpty()
                || txtMatKhauCu.getText().isEmpty()
                || txtMatKhauMoi1.getText().isEmpty()
                || txtMatKhauMoi2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn Nhập Thiếu Thông Tin");
            return false;
        }
        return true;
    }

    void clear() {
        txtMatKhauCu.setText("");
        txtMatKhauMoi1.setText("");
        txtMatKhauMoi2.setText("");
        txtNhapCode.setText("");
        code();
    }
    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void ckbHienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbHienActionPerformed
        // TODO add your handling code here:
        if (ckbHien.isSelected()) {
            txtMatKhauCu.setEchoChar((char) 0);
            txtMatKhauMoi1.setEchoChar((char) 0);
            txtMatKhauMoi2.setEchoChar((char) 0);
        } else {
            txtMatKhauCu.setEchoChar('*');
            txtMatKhauMoi1.setEchoChar('*');
            txtMatKhauMoi2.setEchoChar('*');
        }
    }//GEN-LAST:event_ckbHienActionPerformed

    private void btnCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeActionPerformed
        // TODO add your handling code here:
        code();
    }//GEN-LAST:event_btnCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoiMatKhauJDialog dialog = new DoiMatKhauJDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCode;
    private javax.swing.JButton btnDMK;
    private javax.swing.JButton btnHuy;
    private javax.swing.JCheckBox ckbHien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhauCu;
    private javax.swing.JPasswordField txtMatKhauMoi1;
    private javax.swing.JPasswordField txtMatKhauMoi2;
    private javax.swing.JTextField txtNhapCode;
    // End of variables declaration//GEN-END:variables
}
