/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import UTILS.Auth;
import UTILS.MsgBox;
import UTILS.XImage;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author DELL
 */
public class MainForm extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.OpenWellcome();
        this.OpenDangNhap();
        init();
        Thread timer = new Thread(this);
        timer.start();
    }

    void init() {
        setLocationRelativeTo(null);
        setTitle("Chương Trình Quản Lý Coffe");
        setIconImage(XImage.getAppIcon());
        setRole();
        this.setAccount();
//        setExtendedState(MainForm.MAXIMIZED_BOTH);
        getanh();
    }

    @Override
    public void run() {
        while (true) {
            Date now = new Date();
            SimpleDateFormat fm = new SimpleDateFormat("hh:mm:ss:aa");
            String time = fm.format(now);
            lbldongho.setText(time);

            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {

            }
        }
    }

    void getanh() {
        BufferedImage bt = null;
        JLabel lb = new JLabel();
        lb.setPreferredSize(new Dimension(panelAnh.getWidth(), panelAnh.getHeight()));
        try {
            bt = ImageIO.read(getClass().getClassLoader().getResource("images/cfdangnhap.jpg"));
            lb.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        } catch (IOException e) {

        }
        ImageIcon imgicon = new ImageIcon(bt);
        Image img = imgicon.getImage();
        lb.setIcon(new ImageIcon(img.getScaledInstance(panelAnh.getWidth(), panelAnh.getHeight(), Image.SCALE_SMOOTH)));
        panelAnh.removeAll();
        panelAnh.setLayout(new BorderLayout());
        panelAnh.add(lb);
        panelAnh.setPreferredSize(new Dimension(panelAnh.getWidth(), panelAnh.getHeight()));
        panelAnh.repaint();
    }

    void setRole() {
        if (Auth.isLogin()) {
            lblRole.setText(Auth.user.isVaiTro() ? "Quản Lý" : "Nhân Viên");

        } else {
            lblRole.setText(!Auth.user.isVaiTro() ? "Quản Lý" : "Nhân Viên");

        }
    }

    void setAccount() {
        if (!Auth.isManager()) {
            btnNhanVien.setVisible(false);
            jmenuthongke.setVisible(false);
            menuNhanVien.setVisible(false);
        } else {
            btnNhanVien.setVisible(true);
            jmenuthongke.setVisible(true);
            menuNhanVien.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        panelAnh = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNhanVien = new javax.swing.JButton();
        btnLoaiSP = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnKH = new javax.swing.JButton();
        btnBanHang = new javax.swing.JButton();
        btnGioiThieu = new javax.swing.JButton();
        btnDanGXuat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbldongho = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuDangXuat = new javax.swing.JMenuItem();
        menuDoiMK = new javax.swing.JMenuItem();
        menuThoat = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuNhanVien = new javax.swing.JMenuItem();
        menuDoUong = new javax.swing.JMenuItem();
        menuBanHang = new javax.swing.JMenuItem();
        jmenuthongke = new javax.swing.JMenu();
        menuTK = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAnh.setPreferredSize(new java.awt.Dimension(1000, 600));
        panelAnh.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelAnh, java.awt.BorderLayout.CENTER);

        jToolBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("");
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToolBar1.setName(""); // NOI18N

        btnNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNhanVien.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Clien list.png")); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNhanVien);

        btnLoaiSP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnLoaiSP.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Box.png")); // NOI18N
        btnLoaiSP.setText("Loại Sản Phẩm");
        btnLoaiSP.setFocusable(false);
        btnLoaiSP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLoaiSP.setPreferredSize(new java.awt.Dimension(61, 49));
        btnLoaiSP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLoaiSP);

        btnSanPham.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSanPham.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Home.png")); // NOI18N
        btnSanPham.setText("Sản Phẩm");
        btnSanPham.setFocusable(false);
        btnSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSanPham.setPreferredSize(new java.awt.Dimension(61, 49));
        btnSanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSanPham);

        btnKH.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnKH.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\User.png")); // NOI18N
        btnKH.setText("Khách Hàng");
        btnKH.setFocusable(false);
        btnKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKH);

        btnBanHang.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnBanHang.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Coins.png")); // NOI18N
        btnBanHang.setText("Bán Hàng");
        btnBanHang.setFocusable(false);
        btnBanHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBanHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBanHang);

        btnGioiThieu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnGioiThieu.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Online.png")); // NOI18N
        btnGioiThieu.setText("Giới Thiệu");
        btnGioiThieu.setFocusable(false);
        btnGioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGioiThieuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGioiThieu);

        btnDanGXuat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDanGXuat.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Exit.png")); // NOI18N
        btnDanGXuat.setText("Đăng Xuất");
        btnDanGXuat.setFocusable(false);
        btnDanGXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDanGXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDanGXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanGXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDanGXuat);

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Exit button.png")); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setFocusable(false);
        btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThoat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 51, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Tick.png")); // NOI18N
        jLabel1.setText("Hệ Thống Quản Lý Coffe");

        lbldongho.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbldongho.setForeground(new java.awt.Color(255, 255, 255));
        lbldongho.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Alarm.png")); // NOI18N
        lbldongho.setText("00:00:00");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Role:");

        lblRole.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setText("Quản Lý / Nhân Viên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 692, Short.MAX_VALUE)
                .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lbldongho)
                        .addComponent(jLabel3)
                        .addComponent(lblRole))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        menu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jMenu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu2.setText("Hệ Thống");

        menuDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuDangXuat.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Exit.png")); // NOI18N
        menuDangXuat.setText("Đăng Xuất");
        menuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangXuatActionPerformed(evt);
            }
        });
        jMenu2.add(menuDangXuat);

        menuDoiMK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuDoiMK.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Refresh.png")); // NOI18N
        menuDoiMK.setText("Đỗi Mật Khẩu");
        menuDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDoiMKActionPerformed(evt);
            }
        });
        jMenu2.add(menuDoiMK);

        menuThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuThoat.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Exit button.png")); // NOI18N
        menuThoat.setText("Thoát");
        menuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThoatActionPerformed(evt);
            }
        });
        jMenu2.add(menuThoat);

        menu.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu3.setText("Quản Lý");

        menuNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuNhanVien.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Clien list.png")); // NOI18N
        menuNhanVien.setText("Nhân Viên");
        menuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhanVienActionPerformed(evt);
            }
        });
        jMenu3.add(menuNhanVien);

        menuDoUong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuDoUong.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Home.png")); // NOI18N
        menuDoUong.setText("Sản Phẩm");
        menuDoUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDoUongActionPerformed(evt);
            }
        });
        jMenu3.add(menuDoUong);

        menuBanHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuBanHang.setIcon(new javax.swing.ImageIcon("E:\\Java\\duan1\\src\\main\\Resources\\images\\Coins.png")); // NOI18N
        menuBanHang.setText("Bán Hàng");
        menuBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBanHangActionPerformed(evt);
            }
        });
        jMenu3.add(menuBanHang);

        menu.add(jMenu3);

        jmenuthongke.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jmenuthongke.setText("Thống Kê");

        menuTK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuTK.setText("Thống Kê ");
        menuTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTKActionPerformed(evt);
            }
        });
        jmenuthongke.add(menuTK);

        menu.add(jmenuthongke);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDoiMKActionPerformed
        // TODO add your handling code here:
        this.openDoiMatKhau();
    }//GEN-LAST:event_menuDoiMKActionPerformed

    private void menuDoUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDoUongActionPerformed
        // TODO add your handling code here:
        this.OpenSanPham();

    }//GEN-LAST:event_menuDoUongActionPerformed

    private void menuBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBanHangActionPerformed
        // TODO add your handling code here:
        OpenBanHang();
    }//GEN-LAST:event_menuBanHangActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.ketThuc();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDanGXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanGXuatActionPerformed
        // TODO add your handling code here:
        this.DangXuat();
    }//GEN-LAST:event_btnDanGXuatActionPerformed

    private void menuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThoatActionPerformed
        // TODO add your handling code here:
        this.ketThuc();
    }//GEN-LAST:event_menuThoatActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        this.openNhanVien();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void menuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhanVienActionPerformed
        // TODO add your handling code here:
        this.openNhanVien();
    }//GEN-LAST:event_menuNhanVienActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        // TODO add your handling code here:
        OpenSanPham();
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        // TODO add your handling code here:
        OpenBanHang();
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void menuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangXuatActionPerformed
        // TODO add your handling code here:
        DangXuat();

    }//GEN-LAST:event_menuDangXuatActionPerformed

    private void btnKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHActionPerformed
        // TODO add your handling code here:
        openKhachHang();
    }//GEN-LAST:event_btnKHActionPerformed

    private void btnLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiSPActionPerformed
        // TODO add your handling code here:
        OpenLoaiSanPham();
    }//GEN-LAST:event_btnLoaiSPActionPerformed

    private void menuTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTKActionPerformed
        // TODO add your handling code here:
        openThongKe();
    }//GEN-LAST:event_menuTKActionPerformed

    private void btnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGioiThieuActionPerformed
        // TODO add your handling code here:
        OpenGT();
    }//GEN-LAST:event_btnGioiThieuActionPerformed
    void DangXuat() {
        if (Auth.isLogin()) {
            if (MsgBox.confirm(this, "Bạn có muốn đăng xuất không?")) {
                Auth.clear();
                new DangnhapJDialog(this, true).setVisible(true);
                this.setRole();
                this.setAccount();
            }
        } else {
            Auth.clear();
            MsgBox.alert(this, "Bạn đã đăng xuất");
        }

    }

    void openKhachHang() {
        new KhachHangDialog(this, true).setVisible(true);
    }

    void OpenGT() {
        new GioiThieuDiaLog(this, true).setVisible(true);
    }

    void startDongHo() {
        SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
        new Timer(1000, (ActionEvent e) -> {
            lbldongho.setText(formater.format(new Date()));
        }).start();
    }

    void openDoiMatKhau() {
        if (Auth.isLogin()) {//kiểm tra người dùng đã dắng nhập ? 
            new DoiMatKhauJDialog(this, true).setVisible(true);
        }
    }

    void OpenWellcome() {
        new ChaoDialog(this, true).setVisible(true);
    }

    void OpenDangNhap() {
        new DangnhapJDialog(this, true).setVisible(true);
    }

    void ketThuc() {
        if (MsgBox.confirm(this, "Bạn muốn kết thúc làm việc?")) {
            System.exit(0);
        }
    }

    void openNhanVien() {
        if (Auth.isLogin()) {
            new NhanVienDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void OpenSanPham() {
        new SanPhamDiaLog(this, true).setVisible(true);
    }

    void OpenLoaiSanPham() {
        new LoaiSPDiaLog(this, true).setVisible(true);
    }

    void OpenBanHang() {
        new BanHangDiaLog(this, true).setVisible(true);
    }

    void openThongKe() {
        new ThongkeDialog(this, true).setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            new MainForm().setVisible(true);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainForm().setVisible(true);
//                
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnDanGXuat;
    private javax.swing.JButton btnGioiThieu;
    private javax.swing.JButton btnKH;
    private javax.swing.JButton btnLoaiSP;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu jmenuthongke;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuBanHang;
    private javax.swing.JMenuItem menuDangXuat;
    private javax.swing.JMenuItem menuDoUong;
    private javax.swing.JMenuItem menuDoiMK;
    private javax.swing.JMenuItem menuNhanVien;
    private javax.swing.JMenuItem menuTK;
    private javax.swing.JMenuItem menuThoat;
    private javax.swing.JPanel panelAnh;
    // End of variables declaration//GEN-END:variables
}
